# Application Launcher with Nix profile environment
unbindsym $mod+d
bindsym $mod+d exec env XDG_DATA_DIRS=$HOME/.nix-profile/share:${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/} PATH=$HOME/.nix-profile/bin:${PATH} rofi -show combi -combi-modes drun#run -modes combi
