# Swayidle native idle and lock configuration
set $lock_cmd ~/.config/sway/scripts/lock.sh

exec_always "pkill -xu $USER -x swayidle; swayidle -w \
    timeout 300 '$lock_cmd' \
    timeout 330 'swaymsg \"output * dpms off\"' \
         resume 'swaymsg \"output * dpms on\"' \
    before-sleep '$lock_cmd' \
    after-resume 'swaymsg \"output * dpms on\"' \
    unlock 'swaymsg \"output * dpms on\"'"

