# Swayidle native idle and lock configuration
set $lock_cmd ~/.config/sway/scripts/lock.sh

exec_always "pkill -xu $USER -x swayidle; swayidle -w \
    timeout 300 $lock_cmd \
    timeout 310 'swaymsg \"output * power off\"' \
         resume 'swaymsg \"output * power on\"' \
    before-sleep $lock_cmd \
    after-resume 'swaymsg \"output * power on\"' \
    unlock 'swaymsg \"output * power on\"' \
    lock $lock_cmd"
