# Swayidle native idle and lock configuration
exec_always "pkill -xu $USER swayidle; swayidle -w \
    timeout 300 'swaylock -f -c 1e1e2e' \
    timeout 305 'swaymsg \"output * dpms off\"' \
         resume 'swaymsg \"output * dpms on\"' \
    before-sleep 'swaylock -f -c 1e1e2e' \
    lock 'swaylock -f -c 1e1e2e'"
