# Unbind default sway exit prompt and bind to Rofi Powermenu
unbindsym $mod+Shift+e
bindsym $mod+Shift+e exec /home/phamnv/.config/rofi/powermenu.sh

# Lock screen & turn off monitors shortcut
unbindsym $mod+$right
bindsym $mod+l exec /home/phamnv/.config/sway/scripts/lock.sh
