# Autostart Flameshot daemon
exec flameshot

# Screenshot Shortcuts via Flameshot
# Explicitly unbind default grimshot shortcuts on host
unbindsym Print
unbindsym Alt+Print
unbindsym Ctrl+Print

# Sway window rules for Flameshot overlay GUI
for_window [app_id="flameshot"] floating enable, border pixel 0, mouse_warping no

# Bind Flameshot shortcuts
bindsym Print exec flameshot gui
bindsym $mod+Shift+s exec flameshot gui
bindsym Shift+Print exec flameshot full -c
bindsym Ctrl+Print exec flameshot gui --delay 2000
