# Hyprpaper Configuration
# Managed by ~/dev/dotfiles

preload = /var/home/phamnv/.config/sway/wallpapers/ghibli-day-station.jpg
preload = /var/home/phamnv/.config/sway/wallpapers/ghibli-midnight-station.jpg

# Set default wallpaper for all monitors
wallpaper = ,/var/home/phamnv/.config/sway/wallpapers/ghibli-day-station.jpg

# Disable splash text
splash = false
