# Hyprpaper Configuration
# Managed by ~/dev/dotfiles

wallpaper {
    monitor =
    path = /var/home/phamnv/.config/sway/wallpapers/ghibli-day-station.jpg
    fit_mode = cover
}

# Disable splash text and ensure IPC is on
splash = false
ipc = true
