# Floating Window Rules for Utilities
for_window [app_id="blueman-manager"] floating enable, resize set 700 500, move position center
for_window [app_id="Blueman-manager"] floating enable, resize set 700 500, move position center
for_window [app_id="pavucontrol"] floating enable, resize set 700 500, move position center
for_window [title="Bluetooth Devices"] floating enable, resize set 700 500, move position center
